name: system_idle_linux
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/unitedideasco/system_idle.git
homepage: https://github.com/unitedideasco/

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

# Add regular dependencies here.
dependencies:
  system_idle_platform_interface: ^1.0.0

dev_dependencies:
  ffigen: ^15.0.0

flutter:
  plugin:
    implements: system_idle
    platforms:
      linux:
        ffiPlugin: true
