name: system_idle_linux
description: The Linux implementation of the system_idle package to determine when the user has been idle.
version: 1.0.0
repository: https://github.com/unitedideasco/system_idle.git
homepage: https://github.com/unitedideasco/

environment:
  sdk: ^3.5.0
  flutter: '>= 3.24.0'

resolution: workspace
dependencies:
  system_idle_platform_interface: ^1.0.0

dev_dependencies:
  ffigen: ^16.0.0

flutter:
  plugin:
    implements: system_idle
    platforms:
      linux:
        ffiPlugin: true
