name: system_idle_linux
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  system_idle_platform_interface: ^1.0.0

dependency_overrides:
  system_idle_platform_interface:
    path: ../system_idle_platform_interface

dev_dependencies:
  ffigen: ^13.0.0

flutter:
  plugin:
    implements: system_idle
    platforms:
      linux:
        ffiPlugin: true
