name: system_idle_macos
description: The MacOS implementation of the system_idle package to determine when the user has been idle from their device.
version: 1.0.0
repository: https://github.com/unitedideasco/system_idle.git
homepage: https://github.com/unitedideasco/

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  system_idle_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: system_idle
    platforms:
      macos:
        pluginClass: SystemIdlePlugin
