name: system_idle_platform_interface
description: The platform interface for package:system_idle
version: 1.0.0

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
