name: system_idle_platform_interface
description: The platform interface for package:system_idle
version: 1.0.0
repository: https://github.com/unitedideasco/system_idle.git
homepage: https://github.com/unitedideasco/

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
